import sys

path = 'e:/Gihub/71.Mobile-Harness/src/script.js'
with open(path, 'r', encoding='utf-8') as f:
    content = f.read()

workspace_code = """
        // ========== Agent Workspace ==========
        let agentWorkspaceHandle = null;
        
        document.getElementById("workspaceBtn").addEventListener("click", async () => {
            try {
                if (!window.showDirectoryPicker) {
                    showToast("❌ File System API not supported in this browser.");
                    return;
                }
                agentWorkspaceHandle = await window.showDirectoryPicker({ mode: "readwrite" });
                showToast("📁 Agent Workspace connected! Files generated by the model will be saved here.");
            } catch (err) {
                console.warn(err);
                if (err.name !== "AbortError") {
                    showToast("Error connecting workspace: " + err.message);
                }
            }
        });

        async function writeToWorkspace(path, fileContent) {
            if (!agentWorkspaceHandle) return false;
            try {
                const parts = path.split("/");
                let dir = agentWorkspaceHandle;
                for (let i = 0; i < parts.length - 1; i++) {
                    dir = await dir.getDirectoryHandle(parts[i], { create: true });
                }
                const fileHandle = await dir.getFileHandle(parts[parts.length - 1], { create: true });
                const writable = await fileHandle.createWritable();
                await writable.write(fileContent);
                await writable.close();
                return true;
            } catch (err) {
                console.error("Write error:", err);
                return false;
            }
        }

        async function processWorkspaceArtifacts(rawText) {
            if (!agentWorkspaceHandle) return;
            
            // Match <artifact path="...">...</artifact>
            const xmlRegex = /<artifact\\s+path="([^"]+)">([\\s\\S]*?)<\\/artifact>/g;
            let match;
            while ((match = xmlRegex.exec(rawText)) !== null) {
                const path = match[1];
                const fileContent = match[2];
                try {
                    await writeToWorkspace(path, fileContent);
                    showToast(`✅ Saved ${path} to workspace`);
                } catch(e) {
                    showToast(`❌ Failed to save ${path}: ${e.message}`);
                }
            }

            // Match ```file:filename.ext ... ```
            const mdRegex = /```file:([^\\s]+)\\s*\\n([\\s\\S]*?)```/g;
            while ((match = mdRegex.exec(rawText)) !== null) {
                const path = match[1];
                const fileContent = match[2];
                try {
                    await writeToWorkspace(path, fileContent);
                    showToast(`✅ Saved ${path} to workspace`);
                } catch(e) {
                    showToast(`❌ Failed to save ${path}: ${e.message}`);
                }
            }
        }
"""

content = content.replace('const chatbox = document.getElementById("chatbox");', 'const chatbox = document.getElementById("chatbox");\n' + workspace_code)

submit_hook = """
            await runStreamingResponse({
"""
submit_hook_replacement = """
            const ctx = await runStreamingResponse({
"""
content = content.replace(submit_hook, submit_hook_replacement)

after_hook = """
                onFailure: (error, ctx) => {
                    const errMsg = error.message || "Unknown Error";
                    // escapeHtml (not sanitize): angle-bracketed text in server errors
                    // must display literally instead of being stripped.
                    ctx.responseContainer.insertAdjacentHTML('beforeend', `<br><br><span style='color:#ef4444; font-weight:500;'>⚠️ ${escapeHtml(errMsg)}</span><br><span style='color:#9ca3af; font-size:0.9rem;'>Make sure your local server is running and CORS is enabled.</span>`);
                }
            });
"""
after_hook_replacement = after_hook + """
            if (ctx && ctx.fullRawText) {
                await processWorkspaceArtifacts(ctx.fullRawText);
            }
"""
content = content.replace(after_hook, after_hook_replacement)

with open(path, 'w', encoding='utf-8') as f:
    f.write(content)
